version: 2

models:
  - name: neighborhoods
    description: "Raw bitcoin table"
    columns:
      - name: Date
      - name: Open
      - name: High
      - name: Low
      - name: Close
      - name: Volume
      - name: Market_Cap
