USE ROLE ACCOUNTADMIN;
CREATE OR ALTER WAREHOUSE NYC_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 10
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1;

CREATE OR ALTER DATABASE NYC_Dev;

